-- Enable UUID extension for unique identifiers
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==========================================
-- 1. SAAS & IDENTITY LAYER (Global & Tenant)
-- ==========================================

-- ENUMS for fixed states
CREATE TYPE plan_tier AS ENUM ('starter', 'pro', 'enterprise');
CREATE TYPE org_status AS ENUM ('active', 'trial', 'suspended', 'archived');
CREATE TYPE user_role AS ENUM ('org_admin', 'branch_manager', 'staff');
CREATE TYPE infra_status AS ENUM ('healthy', 'degraded', 'offline');

-- Super Admins (Platform Owners)
CREATE TABLE super_admins (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    mfa_secret VARCHAR(255),
    last_login TIMESTAMP,
    created_at TIMESTAMP DEFAULT NOW()
);

-- Organizations (Tenants)
CREATE TABLE organizations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(50) UNIQUE NOT NULL, -- for subdomains (e.g., burgerking.omnicore.com)
    plan plan_tier DEFAULT 'starter',
    status org_status DEFAULT 'trial',
    stripe_customer_id VARCHAR(255),
    config_settings JSONB DEFAULT '{}', -- Feature flags (e.g., {"kds_enabled": true})
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Branches (Physical Locations)
CREATE TABLE branches (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    organization_id UUID REFERENCES organizations(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    address TEXT,
    timezone VARCHAR(50) DEFAULT 'UTC',
    phone VARCHAR(20),
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT NOW()
);

-- Users (Tenant Staff)
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    organization_id UUID REFERENCES organizations(id) ON DELETE CASCADE,
    branch_id UUID REFERENCES branches(id) ON DELETE SET NULL, -- Null if Org Admin
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    pin_code VARCHAR(10), -- Simple 4-digit PIN for POS/Waiter login
    role user_role NOT NULL,
    full_name VARCHAR(100),
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(organization_id, email) -- Email unique per organization
);

-- ==========================================
-- 2. OPERATIONAL LAYER (Menu & Floor)
-- ==========================================

-- Floor Plan Tables
CREATE TABLE floor_tables (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    organization_id UUID REFERENCES organizations(id) ON DELETE CASCADE,
    branch_id UUID REFERENCES branches(id) ON DELETE CASCADE,
    table_number VARCHAR(10) NOT NULL,
    capacity INT DEFAULT 4,
    x_position INT NOT NULL, -- For UI Canvas
    y_position INT NOT NULL, -- For UI Canvas
    shape VARCHAR(20) DEFAULT 'round', -- 'round', 'rect'
    current_status VARCHAR(20) DEFAULT 'free', -- 'free', 'occupied', 'bill'
    created_at TIMESTAMP DEFAULT NOW()
);

-- Menu Categories
CREATE TABLE categories (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    organization_id UUID REFERENCES organizations(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    sort_order INT DEFAULT 0,
    is_active BOOLEAN DEFAULT true
);

-- Menu Items
CREATE TABLE menu_items (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    organization_id UUID REFERENCES organizations(id) ON DELETE CASCADE,
    category_id UUID REFERENCES categories(id) ON DELETE SET NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    image_url TEXT,
    is_available BOOLEAN DEFAULT true,
    preparation_time_est INT, -- in minutes
    created_at TIMESTAMP DEFAULT NOW()
);

-- ==========================================
-- 3. TRANSACTIONAL LAYER (Orders & KDS)
-- ==========================================

CREATE TYPE order_status AS ENUM ('new', 'prep', 'ready', 'served', 'completed', 'cancelled');

-- Orders (The Ticket)
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Readable ID (e.g., 1001)
    organization_id UUID REFERENCES organizations(id) ON DELETE CASCADE,
    branch_id UUID REFERENCES branches(id) ON DELETE CASCADE,
    table_id UUID REFERENCES floor_tables(id),
    server_id UUID REFERENCES users(id),
    status order_status DEFAULT 'new',
    total_amount DECIMAL(10, 2) DEFAULT 0.00,
    payment_status VARCHAR(20) DEFAULT 'unpaid', -- 'unpaid', 'paid', 'refunded'
    payment_method VARCHAR(20), -- 'card', 'cash'
    created_at TIMESTAMP DEFAULT NOW(),
    completed_at TIMESTAMP
);

-- Order Items (Specific rows on a ticket)
CREATE TABLE order_items (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    organization_id UUID REFERENCES organizations(id) ON DELETE CASCADE,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
    menu_item_id UUID REFERENCES menu_items(id),
    quantity INT NOT NULL DEFAULT 1,
    price_at_time DECIMAL(10, 2) NOT NULL, -- Snapshot price in case menu changes
    modifiers JSONB DEFAULT '[]', -- Array of strings e.g., ["No Onions", "Medium Rare"]
    status order_status DEFAULT 'new', -- For individual item tracking on KDS
    created_at TIMESTAMP DEFAULT NOW()
);

-- ==========================================
-- 4. SUPER ADMIN & MONITORING LAYER
-- ==========================================

-- Infrastructure Monitoring
CREATE TABLE infrastructure_nodes (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    region VARCHAR(50),
    ip_address INET,
    status infra_status DEFAULT 'healthy',
    cpu_load INT,
    memory_usage INT,
    last_heartbeat TIMESTAMP DEFAULT NOW()
);

-- System Audit Logs
CREATE TABLE system_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    severity VARCHAR(10), -- INFO, WARN, ERROR
    service VARCHAR(50), -- 'Auth', 'Billing', 'API'
    organization_id UUID, -- Nullable (if global error)
    message TEXT,
    metadata JSONB,
    created_at TIMESTAMP DEFAULT NOW()
);

-- Billing Invoices
CREATE TABLE invoices (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    organization_id UUID REFERENCES organizations(id),
    amount DECIMAL(10, 2),
    status VARCHAR(20), -- 'paid', 'due'
    pdf_url TEXT,
    due_date DATE,
    created_at TIMESTAMP DEFAULT NOW()
);

-- ==========================================
-- 5. INDEXES FOR PERFORMANCE
-- ==========================================

-- Critical for Multi-tenant performance (RLS)
CREATE INDEX idx_users_org ON users(organization_id);
CREATE INDEX idx_orders_org ON orders(organization_id);
CREATE INDEX idx_orders_branch ON orders(branch_id);
CREATE INDEX idx_items_org ON order_items(organization_id);

-- For KDS Speed
CREATE INDEX idx_orders_status ON orders(status) WHERE status NOT IN ('completed', 'cancelled');

-- For Analytics
CREATE INDEX idx_orders_created ON orders(created_at);